name: Validate datasets

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'
    paths:
      - 'datasets/**.ttl'

jobs:
  shacl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Get changed ttl files in datasets
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: datasets/*.ttl
      - name: checkout lfs files
        run: |
            git lfs fetch
            git lfs checkout
      - name: Build and Validate
        uses: konradhoeffner/shacl@master
        with:
          data: ${{ steps.changed-files-specific.outputs.all_changed_files }}
          shacl: IKG_shacl_shapes.ttl
